[files."/etc/group"]
content ="""root:x:0:
bin:x:1:
daemon:x:2:
sys:x:3:
wheel:x:10:
cdrom:x:11:
mail:x:12:postfix
tape:x:30:
video:x:39:
ftp:x:50:
lock:x:54:
audio:x:63:
nobody:x:99:
users:x:100:
utmp:x:22:
utempter:x:35:
ssh_keys:x:999:
input:x:998:
systemd-journal:x:190:
systemd-network:x:192:
dbus:x:81:
sshd:x:74:
vagrant:x:1000:vagrant"""