[commands."ps axo pid,pcpu,pmem,vsz,rss,tty,stat,stime,time,uid,command"]
stdout = """  PID %CPU %MEM    VSZ   RSS TT       STAT STIME     TIME   UID COMMAND
    1  0.0  1.3 128212  6856 ?        Ss   Aug11 00:00:22     0 /usr/lib/systemd/systemd --switched-root --system --deserialize 21
    2  0.0  0.0      0     0 ?        S    Aug11 00:00:00     0 [kthreadd]
    3  0.0  0.0      0     0 ?        S    Aug11 00:00:01     0 [ksoftirqd/0]
    5  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [kworker/0:0H]
    6  0.0  0.0      0     0 ?        S    Aug11 00:00:00     0 [kworker/u2:0]
    7  0.0  0.0      0     0 ?        S    Aug11 00:00:00     0 [migration/0]
    8  0.0  0.0      0     0 ?        S    Aug11 00:00:00     0 [rcu_bh]
    9  0.0  0.0      0     0 ?        R    Aug11 00:00:04     0 [rcu_sched]
   10  0.0  0.0      0     0 ?        S    Aug11 00:00:02     0 [watchdog/0]
   12  0.0  0.0      0     0 ?        S    Aug11 00:00:00     0 [kdevtmpfs]
   13  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [netns]
   14  0.0  0.0      0     0 ?        S    Aug11 00:00:00     0 [khungtaskd]
   15  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [writeback]
   16  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [kintegrityd]
   17  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [bioset]
   18  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [kblockd]
   19  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [md]
   25  0.0  0.0      0     0 ?        S    Aug11 00:00:00     0 [kswapd0]
   26  0.0  0.0      0     0 ?        SN   Aug11 00:00:00     0 [ksmd]
   27  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [crypto]
   35  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [kthrotld]
   36  0.0  0.0      0     0 ?        S    Aug11 00:00:00     0 [kworker/u2:1]
   37  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [kmpath_rdacd]
   38  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [kpsmoused]
   39  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [ipv6_addrconf]
   59  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [deferwq]
   91  0.0  0.0      0     0 ?        S    Aug11 00:00:00     0 [kauditd]
  233  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [ata_sff]
  237  0.0  0.0      0     0 ?        S    Aug11 00:00:00     0 [scsi_eh_0]
  239  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [scsi_tmf_0]
  240  0.0  0.0      0     0 ?        S    Aug11 00:00:00     0 [scsi_eh_1]
  243  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [scsi_tmf_1]
  256  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [kworker/0:1H]
  316  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [kdmflush]
  317  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [bioset]
  328  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [kdmflush]
  329  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [bioset]
  342  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [bioset]
  343  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfsalloc]
  344  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs_mru_cache]
  345  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-buf/dm-0]
  346  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-data/dm-0]
  347  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-conv/dm-0]
  348  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-cil/dm-0]
  349  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-reclaim/dm-]
  350  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-log/dm-0]
  351  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-eofblocks/d]
  352  0.0  0.0      0     0 ?        S    Aug11 00:00:07     0 [xfsaild/dm-0]
  405  0.0  0.9  32784  4668 ?        Ss   Aug11 00:00:05     0 /usr/lib/systemd/systemd-journald
  426  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [rpciod]
  427  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xprtiod]
  433  0.0  0.8 129596  4164 ?        Ss   Aug11 00:00:00     0 /usr/sbin/lvmetad -f
  436  0.0  0.9  46824  4880 ?        Ss   Aug11 00:00:00     0 /usr/lib/systemd/systemd-udevd
  505  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-buf/sda2]
  506  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-data/sda2]
  507  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-conv/sda2]
  508  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-cil/sda2]
  509  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-reclaim/sda]
  510  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-log/sda2]
  511  0.0  0.0      0     0 ?        S<   Aug11 00:00:00     0 [xfs-eofblocks/s]
  512  0.0  0.0      0     0 ?        S    Aug11 00:00:00     0 [xfsaild/sda2]
  531  0.0  0.2  55496  1060 ?        S<sl Aug11 00:00:01     0 /sbin/auditd
  552  0.0  1.7 216256  8992 ?        Ssl  Aug11 00:00:21     0 /usr/sbin/rsyslogd -n
  553  0.0  1.5 534180  7944 ?        Ssl  Aug11 00:00:00   999 /usr/lib/polkit-1/polkitd --no-debug
  554  0.0  0.3  24248  1712 ?        Ss   Aug11 00:00:01     0 /usr/lib/systemd/systemd-logind
  557  0.0  0.3  32812  1852 ?        Ssl  Aug11 00:00:01    81 /bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
  562  0.0  0.3 115684  1804 ?        S    Aug11 00:00:03   998 /usr/sbin/chronyd
  570  0.0  0.2 195080  1228 ?        Ssl  Aug11 00:00:00     0 /usr/sbin/gssproxy -D
  572  0.0  1.8 760748  9224 ?        Ssl  Aug11 00:00:07     0 /usr/sbin/NetworkManager --no-daemon
  588  0.0  0.3 126276  1676 ?        Ss   Aug11 00:00:01     0 /usr/sbin/crond -n
  593  0.0  0.1 110088   860 tty1     Ss+  Aug11 00:00:00     0 /sbin/agetty --noclear tty1 linux
  612  0.0  3.1 113420 15892 ?        S    Aug11 00:00:00     0 /sbin/dhclient -d -q -sf /usr/libexec/nm-dhcp-helper -pf /var/run/dhclient-eth0.pid -lf /var/lib/NetworkManager/dhclient-5fb06bd0-0bb0-7ffb-
  811  0.0  0.8 106048  4128 ?        Ss   Aug11 00:00:00     0 /usr/sbin/sshd -D -u0
  813  0.0  3.3 562440 16604 ?        Ssl  Aug11 00:00:38     0 /usr/bin/python -Es /usr/sbin/tuned -l -P
  911  0.0  0.4  89596  2152 ?        Ss   Aug11 00:00:01     0 /usr/libexec/postfix/master -w
  913  0.0  0.8  89768  4044 ?        S    Aug11 00:00:00    89 qmgr -l -t unix -u
 6319  0.0  1.0 145752  5332 ?        Ss   Aug15 00:00:00     0 sshd: vagrant [priv]
 6322  0.0  0.5 146068  2832 ?        S    Aug15 00:00:00  1000 sshd: vagrant@pts/0
 6323  0.0  0.6 116496  3296 pts/0    Ss   Aug15 00:00:00  1000 -bash
24669  0.0  0.8  89700  4024 ?        S    Aug15 00:00:00    89 pickup -l -t unix -u
25424  0.0  0.0      0     0 ?        S    00:01 00:00:00     0 [kworker/0:2]
26884  0.0  0.0      0     0 ?        R    00:31 00:00:00     0 [kworker/0:0]
27889  0.0  0.3 148952  1656 pts/0    R+   00:52 00:00:00  1000 ps axo pid,pcpu,pmem,vsz,rss,tty,stat,stime,time,uid,command"""