
[commands."powershell -c \"Get-HotFix | Select-Object -Property Status, Description, HotFixId, Caption, InstallDate, InstalledBy | ConvertTo-Json\""]
stdout="""
[{
		"Status": null,
		"Description": "Update",
		"HotFixId": "KB4486553",
		"Caption": "http://support.microsoft.com/?kbid=4486553",
		"InstallDate": null,
		"InstalledBy": "NT AUTHORITY\\\\SYSTEM"
	},
	{
		"Status": null,
		"Description": "Update",
		"HotFixId": "KB4462930",
		"Caption": "http://support.microsoft.com/?kbid=4462930",
		"InstallDate": null,
		"InstalledBy": "NT AUTHORITY\\\\SYSTEM"
	},
	{
		"Status": null,
		"Description": "Security Update",
		"HotFixId": "KB4470788",
		"Caption": "http://support.microsoft.com/?kbid=4470788",
		"InstallDate": null,
		"InstalledBy": "NT AUTHORITY\\\\SYSTEM"
	},
	{
		"Status": null,
		"Description": "Update",
		"HotFixId": "KB4480056",
		"Caption": "http://support.microsoft.com/?kbid=4480056",
		"InstallDate": null,
		"InstalledBy": "NT AUTHORITY\\\\SYSTEM"
	},
	{
		"Status": null,
		"Description": "Security Update",
		"HotFixId": "KB4487038",
		"Caption": "http://support.microsoft.com/?kbid=4487038",
		"InstallDate": null,
		"InstalledBy": "NT AUTHORITY\\\\SYSTEM"
	},
	{
		"Status": null,
		"Description": "Update",
		"HotFixId": "KB4482887",
		"Caption": "http://support.microsoft.com/?kbid=4482887",
		"InstallDate": null,
		"InstalledBy": "NT AUTHORITY\\\\SYSTEM"
	}
]
"""