name: goreleaser

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    

jobs:
  goreleaser:
    permissions:
      # Add "contents" to write release
      contents: 'write'
      # Add "id-token" for google-github-actions/auth
      id-token: 'write'

    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIP }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - id: 'gcp_secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v0'
        with:
          secrets: |-
            code_sign_cert_b64:mondoo-base-infra/mondoo_code_sign_certificate_pfx_b64
            code_sign_cert_challenge:mondoo-base-infra/mondoo_code_sign_challenge
      - name: "Write Windows Signing Cert"
        run: |
          cert="$(mktemp -t cert.XXX)"
          base64 -d <<<"$CERT_CONTENTS" > "$cert"
          echo "CERT_FILE=$cert" >> $GITHUB_ENV
        env:
          CERT_CONTENTS: '${{ steps.gcp_secrets.outputs.code_sign_cert_b64 }}'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --timeout 120m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CERT_PASSWORD: ${{ steps.gcp_secrets.outputs.code_sign_cert_challenge }}
      - name: Install RPM packaging dependencies
        run: sudo apt-get install -y rpm reprepro
      - name: Set up GPG for RPM
        run: |
          echo "${{ secrets.GPG_PASSPHRASE }}" > passphrase
          echo "${{ secrets.GPG_PUBKEY }}" > mondoo_gpg2_pub.gpg
          echo "${{ secrets.GPG_PUBKEY }}" | gpg --import --no-tty --batch --yes
          echo "${{ secrets.GPG_SECKEY }}" | gpg --import --passphrase-file passphrase --allow-secret-key-import --pinentry-mode loopback --no-tty --batch --yes
          echo "allow-preset-passphrase" > ~/.gnupg/gpg-agent.conf
          # Find keygrip with 'gpg --list-secret-keys --with-keygrip'
          gpg-connect-agent RELOADAGENT /bye
          echo "${{secrets.GPG_PASSPHRASE}}" | /usr/lib/gnupg2/gpg-preset-passphrase --preset "${{secrets.GPG_KEYGRIP}}"
          rpm --import mondoo_gpg2_pub.gpg
      - name: Sign RPMs
        run: |
          cp scripts/rpmmacros ~/.rpmmacros
          export GPG_TTY=$(tty)
          ls -lR
          rpmsign --addsign dist/*.rpm