name: goreleaser

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    

jobs:
  goreleaser:
    # Add "id-token" for google-github-actions/auth
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIP }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - id: 'gcp_secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v0'
        with:
          secrets: |-
            code_sign_cert_b64url:mondoo-base-infra/mondoo_code_sign_certificate_pfx
            code_sign_cert_challenge:mondoo-base-infra/mondoo_code_sign_challenge
      - name: "Write Windows Signing Cert"
        run: |
          cert="$(mktemp -t cert.XXX)"
          cat <<<"$CERT_CONTENTS" > "$cert"
          echo "CERT_FILE=$cert" >> $GITHUB_ENV
        env:
          CERT_CONTENTS: '${{ steps.gcp_secrets.outputs.code_sign_cert_b64url }}'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --timeout 120m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CERT_PASS: ${{ steps.gcp_secrets.outputs.code_sign_cert_challenge }}
